### ISSUE TITLE
 Online Frequencies

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#10]
# LPPT

## Departure Clearence Frequency Information

- [x] `118.950` `FOR DEP CLEARANCE CONTACT DEL 118.950` *
- [x] `121.750` `FOR DEP CLEARANCE CONTACT GND 121.750` *
- [x] `118.100` `FOR DEP CLEARANCE CONTACT TWR 118.100` *
- [x] `119.100` `ON THE GROUND CONTACT APP 119.100`
- [x] `125.550` `ON THE GROUND CONTACT 125.550`

## Airborne Frequency Information

Apenas é apresentada informação se for diferente da frequência anterior

- [x] `125.125` `AFTER DEP CONTACT 125.125` *
- [x] `119.100` `AFTER DEP CONTACT 119.1` *
- [x] `125.550` `AFTER DEP CONTACT 125.55`

# LPPR

## Departure Clearence Frequency Information

- [x] `118.920` `FOR ATC CLEARANCE CONTACT PORTO DEL` *
- [x] `118.000` `PORTO DEL CLOSED` *
- [x] `121.100` `FREQ 118.0 CLOSED CONTACT FREQ 121.1` *
- [x] `125.550` `ON THE GROUND CONTACT 125.550`

# LPFR

## Departure Clearence Frequency Information

- [ ] `118.575` `GND OPEN 118.575` *
- [x] `120.750` `GND CLOSED` *
- [x] `119.400` `ON THE GROUND CONTACT APP 119.400`
- [x] `125.550` `ON THE GROUND CONTACT 125.550`

# LPMA

## Departure Clearence Frequency Information

- [x] `118.350` `ON THE GROUND CONTACT TWR 118.350` *
- [x] `119.600` `ON THE GROUND CONTACT APP 119.6` *
- [x] `125.550` `ON THE GROUND CONTACT 125.550`

(*) corresponde ao ATIS real

**Comment by becas22** [comment]
Não esquecer que entre a frequência de saída e a da clearance vem o "POSITION UNIFORM"

Frequências Online:

- LPPC_CTR, LPPT_APP, LPPT TWR, LPPT_GND, LPPT_DEL
  'AFTER DEP CONTACT 119.1 (...) FOR DEP CLEARANCE CONTACT DEL 118.950'


- LPPC_CTR, LPPT_APP, LPPT TWR, LPPT_GND
  'AFTER DEP CONTACT 119.1 (...) FOR DEP CLEARANCE CONTACT GND 121.750'

- LPPC_CTR, LPPT_APP, LPPT TWR
  AFTER DEP CONTACT 119.1 (...)DEL FRQ CLOSED, FOR DEP CLEARANCE CONTACT TWR 118.1

- LPPC_CTR, LPPT_APP
  DEL FRQ CLOSED, FOR DEP CLEARANCE CONTACT APP 119.1

- LPPC_CTR
  DEL FRQ CLOSED, FOR DEP CLEARANCE CONTACT 125.550

- LPPT_APP, LPPT TWR, LPPT_GND, LPPT_DEL
  'AFTER DEP CONTACT 119.1 (...) FOR DEP CLEARANCE CONTACT DEL 118.950'

-

**Comment by becas22** [comment]
[FLUXOGRAMA MELHOR QUE COMMENT ANTERIOR](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=ATIS%20LISBOA#R5Vxdd6I6FP01vnaRhEB4tGrndq1O21Hvmo83qlS5g8aFOG3n198AQSCJrbMkkZF56MAhBLLZJ2effNhDg9Xrp9jfLD%2FTeRD1oDV%2F7aFhD0JoOQ77L7W85RZgYZxbFnE457bSMAl%2FB0VBbt2F82BbK5hQGiXhpm6c0fU6mCU1mx%2FH9KVe7JlG9adu%2FEUgGSYzP5KtX8N5suRW4HjlhX%2BCcLEsHu1gO7%2Fy5M9%2BLmK6W%2FMH9iB6zv7ll1d%2BURlv6Xbpz%2BlLxYRGPTSIKU3yo9XrIIhSdAvc8vtuDlzdv3gcrJNjbnARf4%2FkrWh8MGdY8FMaJ0u6oGs%2FGpXW66x9QVqDxc6WySpih4AdBq9h8i01X2F%2B9r24sk7it8ql9PQ7r%2BC%2FIEneOAn8XUKZqXzuHaUbXkf%2BpunrHWwsN23pLp7xUpDzx48XAS9ll0gzDgd0FbC3YWXiIPKT8Fe9ep9zabEvV8LJDjiianT5s3%2F50Y5X2p%2FeTpjl7nZy%2FdCXoC%2BBTdv7sgyTYLLxs5a8MFerg83rDuIkeH0fELml%2FAbb5TTcO2p%2B%2BlIhfcHUZYXvjnU6NgRIzW%2BAeaDCuwrVvvE7St5l1%2FQyD8nMI4aIR6AWt34HXNNurQAXIEPoIsmth6M7Zuhfj8bTB9mrl3T1tNuexaPxsS69N54CjCMBM7n9LOHBWpfUG75NYvozGNCIxsyypuuUjs9hFAkmPwoXa3Y6Y2gEzH6dYhWyuN3nF1bhfJ5xWYV0nd8NgO1YAti2DLatwLoJqIkE9c3DmBmGo0f2d3A36o%2F794NRejwdZPaUoQCQKw9b0iepQ6Ofpo4tIIewhBy0FNC5DUAH5LB835fd9mJoakMRbHM0LVKBy9WXQBWJsKFIBA6Fopvxl6wbmDCTE6U8forZ0SLZt%2FOM3o9wnZAOVgQplffbTTDS1cLIFkkjgGVGQlPayCE64G2TrFfBC0wJ%2B%2BLhFYf%2FdD9sh%2FZETt2tXUWcIQqvJk3EdFfC5aKlpy0IKNeg9AQfac%2FxXnXm3AQQXLktUJ02%2BRg0beMdxet2RXUi63wMLcZpLzcIqcY%2F8vTbQBByZVe%2BMFGvghcZGzWWRf3067iI8YpRY4MxHgpxhyiku64YD2Xtc9ExHgl5O3HM9aCKobxDMT7nZjqyJI%2FoG88snY8h0xfhZV2URfgP8%2B%2BLYSxEdfg9g4x1L38%2ByVIEJVN5vQsvPeYr4TUlqYqHV6eKHx%2FlvqOFEgBYijkmXRoAwW5rAGBBc10qkoXoIRGQkZWJAK%2BFIkCJmTYVgGSV2nEVAIBJzh4vXAHEV7gFw1JQ9HHgGuSra2sJ7O%2FoJtOB3VYEduwZCuwu1gFvm2SpCl7bNgSv%2FffoJtsT3FwxIKpLNtmybOpYUMLiUkfFwJWumGTLOioTrd1BX5yuUnFf20opLRP%2BreqBbUUP7BrqgYmWuZY2DQyo4CWmJvyLh1f6jsF0fCDAnXf%2B3xF1rMkAJ8v%2BjgU41zpfgHMN9QGa%2FdyV%2FfzU4dXs1n4c%2B2%2BVAhsarpNtpebH1FB%2BSiJ8ShsLm3iE8hi9W54d5G9Qfst9U45zLnlxTf9mOqpk1Tyfhlfy6i%2FT2bQrSg3V4kJtybSW1W%2FGHeHU5Pg4mu73JhRV5I7H7xJA%2F0PGekcyNh0BOjtlxX0EyOS6JFfPetgW6TesWsxxIsOPRRfLqZ%2BKiK0aPhcyZWRyDp1c%2FH5U7MlsxKboSAwN9pqHkJy65UIds6CwVQGJyUpzMQvLMSvfy%2FHwb69YSZsdZgtuWjjAiQTlBVVhTJUAeg10HI68vLbjY2zI5DYvKKHfsfQbAYH8BtNvYmiTnd5enSj21Zwl%2FRb7%2FGLi5uj0u17%2B5PSbHFhRYA1vf2RK8r4%2FfO%2B3JMzIRiBMbyGTeXfx7MuVjYTI3nFynn40vHpUeYumUFTwNiMp%2F7T3EScqi9U0h3ofcGL5QtE21lvJq6D%2FLhl76AMYkbFe52WsI%2FJTsbpUl5Dy5Mm2jslYifwGJ%2Bq9A%2Ft7uoO%2ByH3VD3I1hD47LX9lLu%2Fmyx%2FzQ6P%2FAQ%3D%3D)

**Comment by pedro2555** [comment]
Perfect!

**Comment by pedro2555** [comment]
- [ ] Clearance freq should always be displayed if different than departure freq, or if the first clearance delivery freq is offline.

- [ ] Departure freq will be displayed when different from the clearance delivery freq available.

**Comment by becas22** [comment]
[files freq.zip](https://github.com/pedro2555/messagemaker/files/1895528/files.freq.zip)

**Comment by pedro2555** [comment]
closing to update LPPT real ops milestone

missing LPFR GND audio, check issue #40
