### ISSUE TITLE
gnd level cloud layer height display

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#15]
Either one of those:

Either `[CLD] [FEW] {000} [FT]` or `[CLD] [FEW] {0} [FT]`

Refer to test `TestLpptAtis.test_sky_gndlevel()`

**Comment by pedro2555** [comment]
Era fixe ver um print disto no FMC

**Comment by becas22** [comment]
Quando vir tiro

**Comment by pedro2555** [comment]
This is confirmed to be `[CLD] [FEW] {0} [FT]`
