### ISSUE TITLE
Visibility below 9999 not displayed

### ISSUE THREAD

**Issue by becas22** [pedro2555/messagemaker#22]
LPFR 020830Z 23005KT 9000 FEW012 BKN018 15/13 Q1009

**Comment by pedro2555** [comment]
Fixed with a629c20

**Comment by pedro2555** [comment]
All distance and altitudes are to be read as single digits whenever the actual distance or altitude is divisible by 100.

To enable this in Euroscope the following output must be respected:

`0250` `250[MTS]`

`0500` {500}[MTS]
