### ISSUE TITLE
Output dos Transition Levels

### ISSUE THREAD

**Issue by becas22** [pedro2555/messagemaker#25]
Era fixe ter um output de todos os Transition Levels (LPPT, LPPR, LPFR, LPMA) e fosse atualizando à medida que saem METARs novos.
Fixe, fixe, era ter um mini painel no euroscope (um plugin por exemplo).
Dava imenso jeito para controlar LPPC.

**Comment by pedro2555** [comment]
De momento o transition level e calculado com base nas tabelas publicadas pela NAV Portugal, na transition altitude para os aeroportos que referes, e no QNH reportado na METAR.

Nao entendi qual a melhoria a acrescentar, actualizar no Euroscope tbm?

**Comment by becas22** [comment]
O que era mesmo fixe era ter um output de todos os Transition Levels para um sitio que o controlador consiga ver facilmente (Plug-in Euroscope era o melhor).

https://gyazo.com/1c17a802b2ad2e336dfbfff0502cb53b

TIpo aquela tabelinha, mostrar permanentemente o Trasition Level que o programa calcula, porque o TL vai ser sempre diferente nos aeroportos (nem que seja Lisboa e Madeira).

**Comment by pedro2555** [comment]
C'mon, thats what an excel spreasheet is for.
