### ISSUE TITLE
High Intensity Operations parameter

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#37]

**Comment by becas22** [comment]
[HIRO.zip](https://github.com/pedro2555/messagemaker/files/1895433/HIRO.zip)

**Comment by pedro2555** [comment]
Audio added in 7829a5dd376116f0586288800b8898e6d0b80ef6

**Comment by pedro2555** [comment]
use url parameter `&hiro=True`

Only available at LPPT
