### ISSUE TITLE
Expect Transponder Only After pushback parameter

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#38]

**Comment by pedro2555** [comment]
[EXP XPNDR ONLY AT STARTUP raw.zip](https://github.com/pedro2555/messagemaker/files/1914142/EXP.XPNDR.ONLY.AT.STARTUP.raw.zip)

**Comment by pedro2555** [comment]
[AFTER DEP CONTACT 125.125] [EXP XPNDR ONLY AFTER STARTUP]

**Comment by becas22** [comment]
00c57a8185f8c455cc2ab953efe294ed9e6c9873
