### ISSUE TITLE
TSRA

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#39]
[MODERATE THUNDERSTORM WITH RAIN RAW.zip](https://github.com/pedro2555/messagemaker/files/1895630/MODERATE.THUNDERSTORM.WITH.RAIN.RAW.zip)

**Comment by pedro2555** [comment]
`LPPT 101700Z 30011KT 270V330 9000 -TSRA FEW025 SCT030 SCT032CB 11/07 Q1001`

**Comment by becas22** [comment]
[TSRA.zip](https://github.com/pedro2555/messagemaker/files/1895678/TSRA.zip)

**Comment by pedro2555** [comment]
package 1.1
