### ISSUE TITLE
Winds at LPLA not showing

### ISSUE THREAD

**Issue by hmgps** [pedro2555/messagemaker#69]
The winds at LPLA are not present on the typical METAR field and only apear in the RMK field at the end of the METAR as a 2 MIN average. These are not possible to get from the common sources of METAR but can be obtained through http://metars.flyatlantic-va.com/metar?ICAO=LPLA or IPMA's selfBriefing portal.

**Comment by pedro2555** [comment]
#71 adds support for IPMA provided metars. We still need to use the winds in the RMK sections.

We are not using the suggested link, but rather calling IPMA outrselves; I doubt they do it better.
```python
icao = 'LPPT'
url = 'https://brief-ng.ipma.pt/showopmetquery.php'
data = {'icaos': icao, 'type': 'metar'}

response = requests.post(url, data)

metar = re.search(
    f'METAR\ .+$',
    response.text,
    re.MULTILINE,
).group()
```

**Comment by pedro2555** [comment]
Support added in 7e32561
