### ISSUE TITLE
ATIS not working for LPPO airports

### ISSUE THREAD

**Issue by hmgps** [pedro2555/messagemaker#70]
Get this message 
"No answer from %20https://atis%2Dpt.herokuapp.com/?metar=LPPD%20041230Z%2027024KT%209999%20FEW015%2017/13%20Q0996&rwy=30&letter=B&show%5Ffreqs=True&hiro=False&xpndr%5Fstartup=False&rwy%5F35%5Fclsd=False"

**Comment by pedro2555** [comment]
Thats probably Euroscope timing out before the app had time to boot.

Retry. The ATIS is operational.
