### ISSUE TITLE
THE WHOLLY AUDIO ISSUE

### ISSUE THREAD

**Issue by pedro2555** [pedro2555/messagemaker#9]
This a wholly list of all audio files for LPPC's airport atis 

- [x] [ATIS OUT OF SERVICE]

- [x] [LPPT ATIS]

- [x] [LPPR ATIS]

- [x] [LPFR ATIS]

- [x] [LPMA ATIS] 

- [x] [ACK LPPT INFO]

- [x] [ACK LPPR INFO]

- [x] [ACK LPFR INFO]

- [x] [ACK LPMA INFO]

- [x] [EXP ILS APCH]

- [x] [EXP ILS Z APCH]

- [x] [EXP ILS DME APCH]

- [x] [EXP R-NAV APCH]

- [x] [EXP VOR DME APCH] 

- [x] [RWY IN USE 03] 

- [x] [RWY IN USE 21] 

- [x] [RWY IN USE 35] 

- [x] [RWY IN USE 17] 

- [x] [RWY IN USE 28] 

- [x] [RWY IN USE 10] [LPFR ATIS J.zip](https://github.com/pedro2555/messagemaker/files/1878706/LPFR.ATIS.J.zip)

- [x] [RWY IN USE 05] 

- [x] [RWY IN USE 23] [LPMA ATIS N 0630.zip](https://github.com/pedro2555/messagemaker/files/1867407/LPMA.ATIS.N.0630.zip)

- [x] [TL] 

- [x] [WND] 

- [x] [VRB BTN] 

- [x] [DEG] 

- [x] [KT] 

- [x] [MAX]

- [x] [CALM]

- [x] [AND] 

- [x] [VIS] 

- [x] [KM] 

- [x] [CAVOK] 

- [x] [SCT] 

- [x] [BKN] 

- [x] [FEW] 

- [x] [OVC]

- [ ] [CB] 

- [x] [TCU]

- [x] [TEMP] 

- [x] [DP] 

- [x] [QNH]

- [x] [FT]

- [x] `thousand` 

- [x] `hundred` 

- [x] [AFTER LANDING VACATE VIA HN]

- [x] [AFTER LANDING VACATE VIA HS] 

- [x] [MEDIUM AND LIGHT AIRCRAFT EXPECT POSITION U FOR DEPARTURE, IF UNABLE ADVISE BEFORE TAXI] 

- [x] [COMPLY WITH SPEED LIMITATIONS UNLESS OTHERWISE ADVISED BY ATC] 

- [x] [AFTER DEPARTURE CONTACT 119.1] 

- [x] [AFTER DEPARTURE CONTACT 125.550] 

- [x] [AFTER DEPARTURE CONTACT 122.8] 

- [x] [FOR DEPARTURE CLEARANCE CONTACT 118.950] 

- [x] [FOR DEPARTURE CLEARANCE CONTACT 121.750] 

- [x] [FOR DEPARTURE CLEARANCE CONTACT 118.100] 

- [ ] [FOR AIR TRAFFIC CONTROL CLEARANCE CONTACT] [LPPR ATIS F complete.zip](https://github.com/pedro2555/messagemaker/files/1867240/LPPR.ATIS.F.complete.zip)

- [ ] [PORTO DELIVERY] [LPPR ATIS F complete.zip](https://github.com/pedro2555/messagemaker/files/1867240/LPPR.ATIS.F.complete.zip)

- [ ] [TWR]

- [ ] [GND] [LPPT280320181730.zip](https://github.com/pedro2555/messagemaker/files/1862755/LPPT280320181730.zip)

- [ ] [DEL] 

- [ ] [FREQ CLOSED] (@becas22 :Tens um semelhante com DEL FREQ CLOSED, isso está separado e juntam com um AND: [LPPT ATIS O.zip](https://github.com/pedro2555/messagemaker/files/1867151/LPPT.ATIS.O.zip))

- [ ] [RWY WET] (até onde percebi isto é dito sempre que não é dada outra indicação de rain, ie.: `-RA` `-SHRA`)

- [ ] [RWY DAMP] 

- [x] [FEEBLE] ? [LPPR ATIS F complete.zip](https://github.com/pedro2555/messagemaker/files/1867240/LPPR.ATIS.F.complete.zip)

- [x] [RA] [LPPR ATIS F complete.zip](https://github.com/pedro2555/messagemaker/files/1867240/LPPR.ATIS.F.complete.zip)

- [x] [SHRA] [LPPT ARR D DEP Z 0730.zip](https://github.com/pedro2555/messagemaker/files/1867514/LPPT.ARR.D.DEP.Z.0730.zip)

- [x] [RE] 

- [x] [RADZ]

- [x] [BR] 

- [x] [MOD]

- [ ] [HEAVY]

**Comment by pedro2555** [comment]
ls -1 | sed -e 's/\..*$//' | awk '{print "RECORD:"$1":"$1".wav"}'``

**Comment by becas22** [comment]
[files.zip](https://github.com/pedro2555/messagemaker/files/1835331/files.zip)

**Comment by pedro2555** [comment]
[LPPR210320182230.zip](https://github.com/pedro2555/messagemaker/files/1835478/LPPR210320182230.zip)

**Comment by pedro2555** [comment]
[LPPT220320180130.zip](https://github.com/pedro2555/messagemaker/files/1835846/LPPT220320180130.zip)

transponder after push back

contact approach

frequencies closed

**Comment by pedro2555** [comment]
[LPPR240320180900.zip](https://github.com/pedro2555/messagemaker/files/1844662/LPPR240320180900.zip)

[TCU]

**Comment by pedro2555** [comment]
Euroscope URL:

`https://messagemaker.herokuapp.com/?metar=$metar($atisairport)&rwy=$arrrwy($atisairport)&letter=$atiscode`

**Comment by becas22** [comment]
- [ ] []
- [ ] []

**Comment by becas22** [comment]
[files.zip](https://github.com/pedro2555/messagemaker/files/1866246/files.zip)
 Latest audio files

**Comment by becas22** [comment]
[x] [LVP IN FORCE]

[x] [RVR TDZ]

[x] [PRFG]

[x] [FG]

**Comment by becas22** [comment]
[files.zip](https://github.com/pedro2555/messagemaker/files/1882327/files.zip)

**Comment by pedro2555** [comment]
Considering feature complete, any further requirements will be on separated issues
